Refactor setup utility script

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,8 +1,12 @@
-#!/usr/bin/env bash
-set -euo pipefail
-IFS=$'\n\t'
-set -vx
+#!/bin/sh
 
+# Exit if any command fails
+set -e
+
+# Install required languages
+asdf install
+asdf reshim
+
+# Install Ruby dependencies
 bundle install
-
-# Do any other automated setup that you need to do here
+asdf reshim ruby
